apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: nacos
data:
  application.properties: |
    #*************** Spring Boot 配置 ***************
    ### 服务器上下文路径
    server.servlet.contextPath=/nacos
    ### 错误信息显示策略
    server.error.include-message=ALWAYS
    ### Web服务端口
    server.port=8848
    
    #*************** 网络配置 ***************
    ### 服务绑定IP地址
    nacos.inetutils.ip-address=127.0.0.1
    
    #*************** 数据库配置 ***************
    ### 数据库平台类型
    spring.sql.init.platform=postgresql
    ### 数据源数量
    db.num=1
    ### 数据库连接URL
    db.url.0=jdbc:postgresql://172.21.31.16:5432/nacosdb?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    ### 数据库用户名
    db.user.0=nacos
    ### 数据库密码
    db.password.0=nacos
    ### 数据库驱动类名
    db.pool.config.driverClassName=org.postgresql.Driver
    ### 连接池连接超时时间(毫秒)
    db.pool.config.connectionTimeout=30000
    ### 连接池验证超时时间(毫秒)
    db.pool.config.validationTimeout=10000
    ### 连接池最大连接数
    db.pool.config.maximumPoolSize=20
    ### 连接池最小空闲连接数
    db.pool.config.minimumIdle=2
    ### 配置推送最大重试次数
    nacos.config.push.maxRetryTime=50
    
    #*************** 服务发现配置 ***************
    # 服务实例预热开关
    # nacos.naming.data.warmup=true
    # 服务实例过期策略
    # nacos.naming.expireInstance=true
    # 空服务清理间隔(毫秒)
    # nacos.naming.clean.empty-service.interval=60000
    # 空服务过期时间(毫秒)
    # nacos.naming.clean.empty-service.expired-time=60000
    # 元数据过期清理间隔(毫秒)
    # nacos.naming.clean.expired-metadata.interval=5000
    # 元数据过期时间(毫秒)
    # nacos.naming.clean.expired-metadata.expired-time=60000
    # 推送任务延迟时间(毫秒)
    # nacos.naming.push.pushTaskDelay=500
    # 推送任务超时时间(毫秒)
    # nacos.naming.push.pushTaskTimeout=5000
    # 推送任务重试间隔(毫秒)
    # nacos.naming.push.pushTaskRetryDelay=1000
    # 客户端实例过期时间(毫秒)
    # nacos.naming.client.expired.time=180000
    
    #*************** CMDB配置 ***************
    # CMDB数据导出间隔(秒)
    # nacos.cmdb.dumpTaskInterval=3600
    # CMDB事件处理间隔(秒)
    # nacos.cmdb.eventTaskInterval=10
    # CMDB标签同步间隔(秒)
    # nacos.cmdb.labelTaskInterval=300
    # 启动时加载CMDB数据
    # nacos.cmdb.loadDataAtStart=false
    
    #*************** Tomcat配置 ***************
    ### 启用Tomcat MBean注册
    server.tomcat.mbeanregistry.enabled=true
    
    #*************** 监控指标配置 ***************
    # 暴露Prometheus端点
    # management.endpoints.web.exposure.include=prometheus,health
    # 禁用ElasticSearch监控
    management.metrics.export.elastic.enabled=false
    # 禁用InfluxDB监控
    management.metrics.export.influx.enabled=false
    
    #*************** 访问日志配置 ***************
    ### 启用Tomcat访问日志
    server.tomcat.accesslog.enabled=true
    ### 启用日志轮转
    server.tomcat.accesslog.rotate=true
    ### 日志文件日期格式
    server.tomcat.accesslog.file-date-format=.yyyy-MM-dd-HH
    ### 日志输出格式
    server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i
    ### 日志存储路径
    server.tomcat.basedir=file:.
    
    #*************** 安全配置 ***************
    ### 忽略静态资源鉴权
    nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
    ### 认证类型
    nacos.core.auth.system.type=nacos
    ### 启用认证
    nacos.core.auth.enabled=true
    ### 启用认证缓存
    nacos.core.auth.caching.enabled=true
    ### 用户代理白名单
    nacos.core.auth.enable.userAgentAuthWhite=false
    ### 认证密钥
    nacos.core.auth.server.identity.key=client-key
    ### 认证密钥值
    nacos.core.auth.server.identity.value=client-secret
    ### Nacos令牌缓存
    nacos.core.auth.plugin.nacos.token.cache.enable=false
    ### 令牌有效期(秒)
    nacos.core.auth.plugin.nacos.token.expire.seconds=18000
    ### 令牌密钥
    nacos.core.auth.plugin.nacos.token.secret.key=cZZZ3HHuPtKh/jGCEvldJ3KgHsjY0+oBzi9b9ksQvvo=
    
    #*************** LDAP配置 ***************
    # LDAP服务地址
    # nacos.core.auth.ldap.url=ldap://localhost:389
    # LDAP基础DN
    # nacos.core.auth.ldap.basedc=dc=example,dc=org
    # 管理员DN
    # nacos.core.auth.ldap.userDn=cn=admin,${nacos.core.auth.ldap.basedc}
    # 管理员密码
    # nacos.core.auth.ldap.password=admin
    # 用户过滤模板
    # nacos.core.auth.ldap.userdn=cn={0},dc=example,dc=org
    # 过滤前缀
    # nacos.core.auth.ldap.filter.prefix=uid
    # 大小写敏感
    # nacos.core.auth.ldap.case.sensitive=true
    # 部分结果异常处理
    # nacos.core.auth.ldap.ignore.partial.result.exception=false
    
    #*************** 扩展配置 ***************
    # 控制器管理类型
    # nacos.plugin.control.manager.type=nacos
    # 规则存储路径
    # nacos.plugin.control.rule.local.basedir=${nacos.home}
    # Webhook配置
    # nacos.core.config.plugin.webhook.enabled=false
    # 网页hook地址
    # nacos.core.config.plugin.webhook.url=http://localhost:8080/webhook/send?token=***
    # 文件格式校验
    # nacos.core.config.plugin.fileformatcheck.enabled=false
    
    #*************** 网络协议配置 ***************
    # GRPC消息大小限制
    # nacos.remote.server.grpc.sdk.max-inbound-message-size=10485760
    # GRPC保持连接参数
    # nacos.remote.server.grpc.sdk.keep-alive-time=7200000
    # GRPC集群参数
    # nacos.remote.server.grpc.cluster.max-inbound-message-size=10485760
    
    #*************** 集群配置 ***************
    # 服务发现节点列表
    # nacos.member.list=192.168.16.101:8847?raft_port=8807,192.168.16.101?raft_port=8808,192.168.16.101:8849?raft_port=8809
    # 地址服务器重试次数
    # nacos.core.address-server.retry=5
    # 地址服务器域名
    # address.server.domain=jmenv.tbsite.net
    # 地址服务端口
    # address.server.port=8080
    
    #*************** 雪花算法配置 ***************
    # 工作节点ID
    # nacos.core.snowflake.worker-id=
    # 元数据中心地址
    # nacos.core.member.meta.site=
    
    #*************** 控制台配置 ***************
    # 启用控制台界面
    nacos.console.ui.enabled=true