apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: nacos
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - name: client-port
      port: 8848
      targetPort: 8848
      nodePort: 30848
      protocol: TCP
